version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-springboot
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3380:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: