server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3380/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG